version: '3.7'

services: 
  fastapi:
    build: .
    volumes:  
      - .:/wiretrack
    command: "uvicorn wsgi:app --host fastapi --port 8080"
    ports:
      - 8080
    env_file: 
      - ./.env
    depends_on: 
      - db

  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - fastapi

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes: 
  postgres_data: